<script lang="ts">
  type packageType = {
    package: {
      name: string;
      scope: "unscoped" | "scoped";
      version: string;
      description: string;
      keywords: [];
      date: "2021-07-19T20:34:33.914Z";
      links: {
        npm: "https://www.npmjs.com/package/passport-azure-ad";
        homepage: "https://github.com/AzureAD/microsoft-authentication-library-for-js#readme";
        repository: "https://github.com/AzureAD/microsoft-authentication-library-for-js";
        bugs: "https://github.com/AzureAD/microsoft-authentication-library-for-js/issues";
      };
      author: {
        name: "azuread";
        email: "nugetaad@microsoft.com";
        url: "http://microsoft.com/";
        username: "azuread";
      };
      publisher: {
        username: "azuread";
        email: "nugetaad@microsoft.com";
      };
      maintainers: [
        {
          username: "msopentech";
          email: "msopentech@microsoft.com";
        },
        {
          username: "azuread";
          email: "nugetaad@microsoft.com";
        }
      ];
    };
    score: {
      final: 0.6971885108315556;
      detail: {
        quality: 0.8047911709983551;
        popularity: 0.3093410680942503;
        maintenance: 0.9928051019973188;
      };
    };
    searchScore: 0.38966373;
  };

  import { fade } from "svelte/transition";
  import { createEventDispatcher } from "svelte";
  import Button from "./button.svelte";

  const dispatch = createEventDispatcher();
  //type npm={total:Number,results:}
  export let data: packageType = {};
  export let selected;

  $: console.log(selected);
  let show = false;
</script>

<div
  class="container "
  style={selected.has(data.package.name) ? "border-left:solid 10px purple" : ""}
>
  <span>
    <div
      class="collapsible"
      on:click={() => {
        show = !show;
      }}
    >
      <a href={data.package.links.npm} class="truncate name"
        >{data.package.name}</a
      >
      <a href={data.package.links.repository}>v{data.package.version}</a>
      <a href={data.package.links.homepage}>
        <span style="vertical-align: super;">Github</span><img
          src="src/assets/github.png"
          alt="?"
          class="git"
        />
      </a>
      <p>relevance score:{data.score?.final.toFixed(3)}</p>
      <Button
        variant="must"
        on:submit={() => {
          let n = data.package.name + "@" + data.package.version;
          if (!selected.has(n)) selected.add(n);
          else selected.delete(n);
          selected = selected;
        }}>{selected.has(data.package.name) ? "remove" : "add"}</Button
      >
    </div>

    <div class={show ? "content2" : "content"} transition:fade>
      <p>
        {data.package.description}
      </p>
    </div>
  </span>
</div>

<style>
  .truncate {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .collapsible {
    background-color: rgb(28, 124, 79);
    color: white;
    cursor: pointer;
    padding: 1em;
    overflow: hidden;
    width: 200px;
    outline: none;
    font-family: "Lucida Sans", "Lucida Sans Regular", "Lucida Grande",
      "Lucida Sans Unicode", Geneva, Verdana, sans-serif;
    box-shadow: rgba(0, 0, 0, 0.16) 0px 1px 4px;
    color: antiquewhite;
    display: inline-flex;
    flex-wrap: wrap;
    align-items: center;
  }
  .name {
    flex-basis: 3;
    color: #81e82c;
    font-weight: 900;
  }
  .fade-in {
    -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
    animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  } /* ----------------------------------------------
 * Generated by Animista on 2021-10-11 20:43:30
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
  @-webkit-keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }

  .collapsible:hover {
    background-color: lightslategray;
  }
  a {
    color: yellow;
    padding-left: 1em;
  }
  .container {
    margin-bottom: 1em;
    width: calc(500px-2em);
    max-width: 100vw;
    display: flex;
    animation-name: rotate-in-2-cw;
    animation-duration: 4s;
  }
  .content {
    display: none;
  }
  .content2 {
    overflow: hidden;
    text-overflow: ellipsis;
    background-color: #f1f1f1;
    padding: 1em;
  }
  .git {
    width: 1em;
    height: 1em;
    vertical-align: super;
  }
  @media only screen and (min-width: 900px) {
    .container,
    .collapsible {
      width: 800px;
    }
    .collapsible {
      flex-direction: row;
    }
    .git {
      width: 1.5em;
      height: 1.5em;
      vertical-align: auto;
    }
  }
</style>
